import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header";
import { Footer } from "../components/footer";
import { Toaster } from "../components/ui/toaster";
import ClientProvider from "../components/clientProvider";
import { ProgressProviders } from "../components/provider/progress.provider";
import SessionProviderWrapper from "../components/session-provider-wrapper";
import GoogleAuthHandler from "../components/auth/google-auth-handler";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EduManageTTT",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <ClientProvider>
            <ProgressProviders>
              <GoogleAuthHandler />
              <Header />
              <main className="mt-10 mb-10 px-6 md:px-12 lg:px-20">
                {children}
              </main>
              <Footer />
              <Toaster />
            </ProgressProviders>
          </ClientProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
